### ISSUE TITLE
Support osx-arm64

### ISSUE THREAD

**Issue by mfansler** [conda-forge/symfit-feedstock#15]
All the dependencies for this package have either **noarch** or **osx-arm64** builds available through Conda Forge. At a glance, it appears this package should support a **noarch** build configuration, but at the very least a **osx-arm64** version should be included in the recipe.

**Comment by Jhsmit** [comment]
Thanks for pointing this out, I've merged a PR that I'm hoping fixes this

**Comment by Jhsmit** [comment]
Tested the noarch 0.5.3 locally on windows and this works so closing the issue

**Comment by mfansler** [comment]
@Jhsmit thanks! 🤩
